ARG CHAIN_VERSION=latest
ARG SF_VERSION=latest

FROM ghcr.io/streamingfast/dummy-blockchain:$CHAIN_VERSION as chain
FROM ghcr.io/streamingfast/firehose-acme:$SF_VERSION

COPY --from=chain /app/dummy-blockchain /app/dummy-blockchain

COPY tools/fireacme/motd_node_manager /etc/motd
COPY tools/fireacme/scripts/. /usr/local/bin/
